"""Add photo_filename to Notification

Revision ID: 117e198cd394
Revises: 64796e2d3e96
Create Date: 2025-04-09 01:22:00.407329

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '117e198cd394'
down_revision = '64796e2d3e96'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('notification', schema=None) as batch_op:
        batch_op.add_column(sa.Column('photo_filename', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('notification', schema=None) as batch_op:
        batch_op.drop_column('photo_filename')

    # ### end Alembic commands ###
