"""Add acknowledged field to Notification

Revision ID: 45bec5a8eae0
Revises: 117e198cd394
Create Date: 2025-04-10 15:55:53.369921

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '45bec5a8eae0'
down_revision = '117e198cd394'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('notification', schema=None) as batch_op:
        batch_op.add_column(sa.Column('acknowledged', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('notification', schema=None) as batch_op:
        batch_op.drop_column('acknowledged')

    # ### end Alembic commands ###
